#!/usr/bin/env php
<?php

// installed via composer?
if (file_exists($a = __DIR__ . '/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use Filternet\Commands\CheckAlexaCsvFileCommand;
use Filternet\Commands\CheckDnsCommand;
use Filternet\Commands\CheckHttpCommand;
use Filternet\Commands\CheckSniCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->setName('Filternet Utility');
$application->setVersion('1.1.1');
$application->add(new CheckSniCommand());
$application->add(new CheckDnsCommand());
$application->add(new CheckHttpCommand());
$application->add(new CheckAlexaCsvFileCommand());
$application->run();